Animal_Shelter/Models/Animalpic.cs
using Animal_Shelter.Data.Base;
using System.ComponentModel.DataAnnotations;
namespace Animal_Shelter.Models
{
    public class Animal : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePictureURL { get; set; }
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 chars")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }
        //Relationships
        public List<Animalpic_Animal>? Actors_Movies { get; set; }
    }
}

Animal_Shelter/Controllers/AnimalpicsController.cs
using Animal_Shelter.Data;
using Animal_Shelter.Data.Services;
using Animal_Shelter.Data.Static;
using Animal_Shelter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Animal_Shelter.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AnimalpicsController : Controller
    {
        private readonly IAnimalpicsService _service;
        public AnimalpicsController(IAnimalpicsService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //Get Animalpic /Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Animalpic animalpic)
        {
            if (!ModelState.IsValid)
            {
                return View(animalpic);
            }
            await _service.AddAsync(animalpic);
            return RedirectToAction(nameof(Index));
        }
        //Get : Animalpics/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(animalpicDetails);
        }

        //Get Animalpic/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var animalpicDetails = await _service.GetByIdAsync(id);
            if (animalpicDetails == null)
            {
                return View("NotFound");
            }
            return View(animalpicDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Animalpic animalpic)
        {
            if (!ModelState.IsValid)
            {
                return View(animalpic);
            }
            await _service.UpdateAsunc(id, animalpic);
            return RedirectToAction(nameof(Index));
        }

        //Get Animalpic/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var animalpicDetails = await _service.GetByIdAsync(id);
            if (animalpicDetails == null)
            {
                return View("NotFound");
            }
            return View(animalpicDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animalpicDetails = await _service.GetByIdAsync(id);
            if (animalpicDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

Animal_Shelter/Views/Animalpics/Details.cshtml
@model Animalpic
@using System.Globalization;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@if (CultureInfo.CurrentCulture.Name.StartsWith("ar"))
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
      integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N"
      crossorigin="anonymous">
           <style>.cr{direction:rtl;}</style>
}
@{
    ViewData["Title"] = localizer["Add a new animalpic"];
}
<div class="container text cr">
    <div class="col-md-8 offset-2">
        <p>
            <h1 class="text-white">@localizer["Details for"] @Model.FullName </h1>
        </p>
        <div class="container">
            <div class="col-md-8 offset-2">

                <div class="mb-4 text-center">
                    <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                </div>
                <div class="mb-4">
                    <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                    <input asp-for="ProfilePictureURL" class="form-control bg-warning" readonly />
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                </div>
                <div class="mb-4">
                    <label asp-for="FullName" class="control-label text-white"></label>
                    <input asp-for="FullName" class="form-control bg-warning" readonly />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="mb-4">
                    <label asp-for="Bio" class="control-label text-white"></label>
                    <input asp-for="Bio" class="form-control bg-warning" readonly />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a class="btn btn-outline-warning float-lg-end" asp-action="Edit" asp-route-id="@Model.Id">@localizer["Edit"]</a>


                    }

                    <a class="btn btn-outline-light" asp-action="Index" asp-controller="Actors">@localizer["Show All"]</a>
                </div>

            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

Animal_Shelter/Views/Animalpics/Edit.cshtml
@model Animalpic
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Globalization;
@if (CultureInfo.CurrentCulture.Name.StartsWith("ar"))
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
      integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N"
      crossorigin="anonymous">
    <style>
        .cr {
            direction: rtl;
        }</style>
}
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = localizer["Update animalpic"] ;
}
<div class="container text cr">
    <div class="col-md-8 offset-2">
        <p>
            <h1 class="text-white">@localizer["Updatte Animalpic"]</h1>
        </p>
        <div class="container">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="mb-4 text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="mb-4">
                        <label asp-for="ProfilePictureURL" class="control-label text-white"></label>
                        <input asp-for="ProfilePictureURL" class="form-control bg-warning" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="mb-4">
                        <label asp-for="FullName" class="control-label text-white"></label>
                        <input asp-for="FullName" class="form-control bg-warning" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="mb-4">
                        <label asp-for="Bio" class="control-label text-white"></label>
                        <input asp-for="Bio" class="form-control bg-warning" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <input type="submit" value="@localizer["Update"]" class="btn btn-outline-warning float-lg-end" />
                        <a class="btn btn-outline-light" asp-action="Index" asp-controller="Animalpics">@localizer["Show All"]</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Animal_Shelter/Views/Animalpics/Index.cshtml
@model IEnumerable<Animalpic>
@using System.Globalization;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    ViewData["Title"] = localizer["List of Animalpics"];
}
<style>
    .btn-outline-primary:hover {
        background-color: #6f42c1;
        border-color: blueviolet;
        color: white;
    }

    .btn-outline-primary {
        border-color: blueviolet;
        color: blueviolet;
    }
</style>
<div class="row">
    <div class="col-md-9 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center text-white">

                    <th>@Html.DisplayNameFor(model =>model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model =>model.FullName)</th>
                    <th>@Html.DisplayNameFor(model =>model.Bio)</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>@localizer["Actions"]</th>

                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-warning">
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem =>item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem =>item.Bio)
                        </td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <td class="align-middle">
                                <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>@localizer["Edit"] </a> |
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>@localizer["Details"] </a> |
                                <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>@localizer["Delete"] </a>
                            </td>
                        }

                      
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@await Html.PartialAsync("_CreateItem","Animals")